name: Build macOS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25.x"
          cache: true

      - name: Install Fyne CLI
        run: go install fyne.io/tools/cmd/fyne@latest

      - name: Build
        run: |
          cd cmd/when-my-meeting

          fyne package \
            -os darwin \
            -icon ../../internal/assets/icon.png \
            -name "When My Meeting" \
            -app-id com.makaksel.when-my-meeting \
            -app-version 0.1.0 \
            -app-build 1

          codesign --force --deep --sign - "When My Meeting.app"

          # zip -r -X "../../when-my-meeting-macos.zip" "When My Meeting.app"

      - name: Upload ZIP
        uses: actions/upload-artifact@v4
        with:
          name: when-my-meeting-macos
          path: ../../When My Meeting.app
